FROM apache/superset:latest

USER root

RUN pip install pyhive
RUN pip install thrift thrift-sasl

ENV ADMIN_USERNAME $ADMIN_USERNAME
ENV ADMIN_EMAIL $ADMIN_EMAIL
ENV ADMIN_PASSWORD $ADMIN_PASSWORD

COPY ./superset/superset-init.sh /superset-init.sh

COPY ./superset/superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

RUN chown -R superset:superset /app/superset_config.py
RUN chown -R superset:superset /superset-init.sh
RUN chmod +x /superset-init.sh

USER superset
ENTRYPOINT [ "/superset-init.sh" ]